apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-eidas-staging
  namespace: argocd
spec:
  project: eidas
  source:
    repoURL: https://github.com/open-eidas/open-eidas.git
    targetRevision: dev
    path: deploy/helm/open-eidas
    helm:
      valueFiles:
      - values-staging.yaml
      values: |
        ca:
          image:
            tag: 4ff75830669116490527e73091e72d63e0b3ad1a
        tsa:
          image:
            tag: 4ff75830669116490527e73091e72d63e0b3ad1a
        ocsp:
          image:
            tag: 4ff75830669116490527e73091e72d63e0b3ad1a
  destination:
    server: https://kubernetes.default.svc
    namespace: open-eidas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ''
    kind: Secret
    name: open-eidas-generated
    jsonPointers:
    - /data
